// cria função que retorna um array de palavras
let text = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec blandit ex sed augue gravida egestas. Vivamus fermentum consectetur lorem ac facilisis. Nam sed tortor vestibulum velit feugiat consequat. Nam vitae massa sem. Fusce efficitur velit id nulla pretium aliquam. Mauris purus sem, molestie sed diam id, pellentesque pellentesque massa. Aenean molestie sapien nisi. Morbi quis nunc luctus neque hendrerit consectetur et at risus. Suspendisse dignissim, velit non tristique vulputate, dui nibh accumsan risus, sit amet interdum odio felis quis augue. Vivamus eget libero laoreet orci pretium venenatis ut id risus. Integer mollis hendrerit vehicula. Suspendisse magna arcu, feugiat id lacus a, elementum posuere libero. Vestibulum sed felis diam. Nunc magna enim, ultrices ut porta id, viverra at neque. Nullam ac dolor imperdiet libero lacinia pellentesque sit amet non nunc.

Nulla quis consequat elit. Donec vitae dui non augue auctor blandit. Nam nec mauris tellus. Sed mattis tortor ac condimentum aliquet. Etiam ut diam ipsum. Pellentesque finibus ac sem ac dictum. Vestibulum finibus ante vitae leo efficitur, nec laoreet est volutpat. Nulla sed hendrerit erat. Nunc eu bibendum nulla. Sed mollis arcu justo, non dignissim nunc tincidunt sit amet. In tortor elit, venenatis id sollicitudin ac, ullamcorper sed velit. Phasellus in lorem pretium, malesuada eros sit amet, tempus nibh.

Quisque elementum porta dui eget cursus. Ut ut orci et justo venenatis condimentum tristique interdum nisl. Nunc pulvinar velit sit amet magna interdum porta. Aenean feugiat posuere lacus, a eleifend sapien consequat eget. Sed sollicitudin at elit eget accumsan. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nunc tortor, vestibulum eget aliquam ac, facilisis nec nunc. Suspendisse potenti. Donec porta nibh ligula, at feugiat sem blandit vitae. Etiam convallis placerat fringilla. Aenean lobortis urna ut enim varius, id euismod libero tincidunt. Fusce eu augue id ligula iaculis rhoncus et eu arcu. Vivamus viverra aliquam neque non luctus.

Fusce at dolor placerat, vulputate nibh non, vehicula lorem. Nam sed commodo dolor, id consectetur urna. Integer eget massa eleifend, luctus tellus eu, feugiat ante. Donec dignissim felis ut ex dignissim tempus. Nam eu sem justo. Donec eget hendrerit leo. Maecenas ornare tellus dui, et aliquet arcu luctus vel. Quisque nibh quam, blandit et ante vitae, fringilla rutrum libero. Nulla rutrum metus nec eros pretium, at viverra magna hendrerit. Praesent dictum erat ac lorem ornare fermentum.

Vivamus eget porttitor eros, ut posuere nibh. Morbi a turpis urna. Nunc eu metus at quam molestie sagittis ut dapibus justo. Nullam placerat dolor laoreet eleifend luctus. Vestibulum efficitur auctor ex, in rutrum metus porttitor quis. Ut vulputate erat quis enim luctus, sit amet maximus nibh luctus. Aenean quis mattis elit. Ut gravida blandit nulla, at varius urna viverra sit amet. Fusce ultricies, justo at porta imperdiet, massa odio porta neque, in ultricies lectus lorem ac nisi. Aliquam interdum facilisis neque, nec lacinia enim malesuada nec. Curabitur nec odio quis nisi venenatis pretium eu eu ante. Etiam non enim eleifend, aliquet ligula quis, volutpat tellus. Aenean vitae dui iaculis, hendrerit ex nec, tempor nulla.

Nulla facilisi. Etiam finibus luctus mollis. Curabitur placerat placerat porttitor. Integer eu dapibus est. Aliquam arcu lectus, rhoncus eu tempus id, lobortis non lacus. Quisque luctus leo molestie neque mattis, dapibus euismod justo auctor. Nam at odio nec felis fermentum suscipit. Morbi id est hendrerit, lacinia quam vestibulum, vulputate justo. Nulla tristique lorem diam, non scelerisque felis bibendum in. Praesent at felis et ipsum congue luctus et ac ipsum. Curabitur sollicitudin a orci quis pretium. Sed eleifend, purus posuere egestas feugiat, ligula justo placerat dolor, nec scelerisque ligula nibh sit amet dolor. Ut sapien urna, rutrum ut tincidunt a, lobortis nec mauris.

Nunc non tellus non urna pellentesque suscipit non eu augue. Quisque tincidunt, nulla eget ultrices auctor, magna risus semper quam, quis consequat orci diam ac nisl. Sed ut massa eget justo ultricies consequat. Nunc sodales nisi in erat imperdiet, a blandit quam imperdiet. Nulla vel molestie massa. Aliquam nec est enim. Integer eleifend dolor in condimentum efficitur. Aliquam ornare dignissim orci, et euismod diam. Duis bibendum lectus sit amet eros vehicula, sed auctor lacus facilisis. Cras vulputate maximus mauris ut dapibus. Maecenas id mi orci.

Suspendisse eu tortor erat. Nunc venenatis non ligula sed tempor. Mauris ut facilisis turpis. Phasellus condimentum diam quis elit venenatis, in maximus velit aliquam. Donec venenatis ut neque ac rhoncus. Proin fringilla libero in condimentum tempor. Donec non cursus elit. Nulla lorem eros, egestas a ornare at, aliquet eget tortor. Pellentesque interdum faucibus odio at porttitor. Vestibulum lorem leo, viverra nec ligula et, dignissim eleifend eros. Mauris fermentum semper diam, ac maximus purus aliquam at. Nullam iaculis nisl vel tempor interdum. Ut porta lectus nisi, sed dictum mi aliquet non. Donec purus tellus, fringilla a feugiat vitae, lacinia vel nunc.

Duis dignissim ut diam in imperdiet. Etiam a turpis elementum lorem commodo aliquam congue lacinia ipsum. Integer odio neque, feugiat quis eros at, convallis rhoncus tellus. Aliquam ac sem pellentesque, dignissim diam eu, ullamcorper neque. Sed id lacus eu metus sollicitudin ullamcorper a sit amet lectus. Maecenas et enim lacus. Nunc rutrum vulputate nisl ut elementum. Maecenas mauris diam, feugiat sit amet venenatis at, malesuada vel odio. Maecenas eu venenatis leo. Etiam sed consectetur mauris. Sed nec facilisis mi, at auctor ipsum.

Aliquam tempor faucibus ante ut volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse pharetra nisl non nulla congue, non ultrices dui faucibus. Sed eget venenatis libero. In mollis ornare libero sit amet accumsan. Praesent felis metus, sollicitudin sed faucibus nec, tristique at ipsum. Vestibulum vehicula leo at ex pretium, id interdum enim ultrices. Fusce sodales feugiat dui, nec volutpat diam vehicula sed. Cras non dapibus ipsum, a volutpat urna. Morbi consectetur commodo neque in lobortis. Etiam nec nibh interdum, vestibulum velit id, varius purus. Suspendisse fermentum eros non auctor finibus. In mauris risus, pharetra et fermentum id, pellentesque in neque. Suspendisse potenti.

Ut ut nisi at quam varius viverra efficitur eu dui. Aenean sed arcu posuere, finibus ante at, blandit orci. Sed ex mauris, egestas ac dictum a, mattis a tellus. Morbi quis nisi sit amet sem laoreet scelerisque. Pellentesque aliquam id justo at varius. Ut placerat malesuada ullamcorper. Nullam tincidunt id arcu in posuere. Nam congue turpis lorem, non imperdiet felis gravida non.

Fusce placerat diam ante, tristique convallis diam molestie ut. Nam turpis sapien, interdum eget ante iaculis, congue viverra magna. Pellentesque dapibus magna elit, vel pharetra ipsum fermentum sed. Sed vitae condimentum nulla, et ultrices libero. Mauris porttitor sodales convallis. Nullam urna diam, scelerisque ut consequat non, vulputate vel massa. Nunc vitae accumsan enim. Vestibulum ullamcorper rhoncus placerat.

Donec vestibulum leo velit, et tincidunt mi cursus eget. Cras nec elit efficitur, tempus purus nec, ultrices metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam ante eros, luctus id orci vitae, sodales tempor ligula. Praesent sollicitudin leo vel ligula tristique malesuada. Pellentesque hendrerit tellus lectus, a dignissim tellus viverra et. Nulla venenatis ultricies vehicula.

Fusce ex tellus, suscipit eu quam sed, pretium venenatis tellus. Integer mattis justo sit amet viverra aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam pellentesque turpis pulvinar erat pretium maximus. Praesent sed ligula iaculis, fringilla diam tempus, suscipit orci. Nulla id erat eget nibh pulvinar ornare. Nunc non rutrum nisi, vel aliquam tellus. Quisque volutpat turpis ac pharetra venenatis. Nam et pharetra lacus, sit amet molestie lacus. Ut nec porttitor sapien. Sed sed massa eu massa pellentesque porttitor. Quisque eu malesuada tortor. Etiam sit amet lacus vel magna interdum euismod. Vivamus elementum vestibulum risus, a efficitur nibh laoreet non.

Donec tellus eros, lacinia in congue a, dignissim sit amet urna. Phasellus vitae elit sit amet neque finibus pharetra nec vel elit. Cras vitae ligula eros. Mauris sagittis consectetur egestas. Suspendisse mollis, mauris a venenatis varius, diam urna gravida sem, at dapibus ante augue non diam. Nam pulvinar, mauris non dictum porta, est neque commodo orci, eu placerat erat libero sit amet dolor. Suspendisse efficitur sapien nec leo tempor lacinia. Nunc tincidunt, diam non posuere volutpat, leo ligula iaculis ante, luctus commodo nunc nisl id ex. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas eget turpis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eget libero ex. Ut consequat imperdiet risus et porta. Aenean ut tellus nisl.

Proin id vulputate dui. Donec viverra elit ut tortor pulvinar, pulvinar vestibulum est mollis. Sed urna nisl, sagittis id tempus nec, posuere et nibh. Pellentesque aliquet, ante quis blandit convallis, nisi tortor dignissim metus, eu tempus justo felis ut purus. Quisque volutpat eros in sagittis ullamcorper. In lobortis vehicula ligula sed maximus. Donec tristique tincidunt neque.

Sed gravida a nisi quis molestie. Nunc nec neque tortor. Praesent eleifend, dolor ut venenatis pellentesque, dolor odio pharetra lacus, sed sodales purus nibh id nisi. Praesent pulvinar tempor ligula, ut faucibus metus sollicitudin non. Morbi congue mi id erat pellentesque mollis. Nullam varius vitae nunc nec sagittis. Ut sollicitudin in massa ac scelerisque. Etiam mattis lacinia laoreet. Suspendisse vitae urna eu eros convallis mattis quis nec sem. Suspendisse vulputate vel est non sodales. Praesent ac luctus est, ac ultricies massa.

Proin congue massa lacinia orci condimentum dignissim. Nulla iaculis risus sed dui viverra, in sodales urna mollis. Nam iaculis velit libero. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et lectus id eros elementum luctus. Pellentesque et sollicitudin ipsum, vitae venenatis diam. Ut quam massa, auctor non hendrerit at, semper non turpis. Cras vulputate, odio a auctor venenatis, leo neque facilisis ipsum, ac imperdiet nunc odio a eros. Phasellus ut felis velit. Vivamus turpis purus, volutpat ac consectetur id, lobortis ut neque. Sed ac eros dapibus, tincidunt orci ut, scelerisque ligula. Etiam dui nunc, tempor ac gravida at, efficitur eu lectus. Sed maximus eros eu justo ullamcorper, ac commodo justo mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed pretium eros quis arcu lobortis, eu venenatis nisl finibus. In condimentum condimentum commodo.

Morbi tristique maximus egestas. Phasellus pretium, erat ac ultrices tristique, lectus ipsum iaculis lacus, consequat porttitor neque dui a felis. Pellentesque sed vestibulum lacus. Aliquam eu accumsan enim, at congue arcu. Nam volutpat vitae nunc nec venenatis. Vestibulum turpis lorem, posuere nec sapien vel, pretium placerat dolor. Aenean vel convallis enim, eu imperdiet elit. Nullam sapien augue, pharetra ultrices nunc vitae, dapibus tempus lacus.

Vivamus quis bibendum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam at lobortis nulla. Nam rhoncus mi lectus, et tempor velit sagittis vitae. Nulla elit eros, vestibulum ac condimentum in, vulputate eu nisi. Aliquam tristique aliquet felis, ut faucibus lectus scelerisque varius. Fusce tincidunt vestibulum venenatis. Integer feugiat erat ut rutrum tincidunt. Mauris eleifend, tortor ut facilisis mollis, metus enim fermentum mauris, ac placerat purus sem eget diam. Curabitur efficitur gravida tempus. Etiam nec malesuada quam. Ut congue molestie erat in aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id nisi finibus, viverra magna in, dignissim nulla. Praesent dictum turpis metus, ut euismod turpis pretium a.`
var words = text.replace(/[,.\n]/g,'')
var array = words.split(' ')

function textAll() {return array }

module.exports = textAll